In [1]:
import csv
import math
import numpy as np
import pandas as pd
import datetime as dt

In [2]:
data = pd.read_csv("qqq.us.txt")

In [3]:
data.head()

Date    Open    High     Low   Close    Volume  OpenInt
0  1999-03-10  45.722  45.750  44.967  45.665  11700414        0
1  1999-03-11  45.994  46.260  44.988  45.880  21670048        0
2  1999-03-12  45.721  45.749  44.406  44.770  19553768        0
3  1999-03-15  45.101  46.103  44.625  46.052  14245348        0
4  1999-03-16  46.253  46.643  45.749  46.447  10971066        0

In [4]:
high=data.loc[:,"High"].to_numpy()

In [5]:
high


array([ 45.75 ,  46.26 ,  45.749, ..., 154.54 , 153.77 , 153.8  ])

In [6]:
type(high)

numpy.ndarray

In [7]:
low=data.loc[:,"Low"].to_numpy()


In [8]:
type(low)

numpy.ndarray

In [9]:
low

array([ 44.967,  44.988,  44.406, ..., 153.62 , 152.11 , 153.06 ])

In [10]:
hml = high - low
print(hml)

[0.783 1.272 1.343 ... 0.92  1.66  0.74 ]


In [11]:
hml = abs(hml)
print(hml)

[0.783 1.272 1.343 ... 0.92  1.66  0.74 ]


In [12]:
hml


array([0.783, 1.272, 1.343, ..., 0.92 , 1.66 , 0.74 ])

In [13]:
opn = data.loc[:,"Open"].to_numpy()

In [14]:
opn

array([ 45.722,  45.994,  45.721, ..., 153.81 , 153.26 , 153.36 ])

In [15]:
cls = data.loc[:,"Close"].to_numpy()

In [16]:
cls

array([ 45.665,  45.88 ,  44.77 , ..., 154.51 , 153.69 , 153.68 ])

In [17]:
omc = opn - cls

In [18]:
bnry_omc = np.zeros(4701)
for i in range(4701):
    if(omc[i] < 0):
        bnry_omc[i]=1
        

In [19]:
print(bnry_omc)

[0. 0. 0. ... 1. 1. 1.]


In [20]:
for i in range(4701):
    print( bnry_omc[i])

0.0
0.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
1.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
1.0
1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
0.0
0.0
1.0
0.0
0.0
1.0
0.0
0.0
1.0
0.0
0.0
1.0
0.0
1.0
0.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
1.0
0.0
1.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
0.0
0.0
1.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0


1.0
1.0
0.0
0.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
1.0
1.0
0.0
1.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
0.0
1.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
1.0
1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
1.0
1.0
0.0
0.0
1.0
0.0
1.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
1.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
1.0
0.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
0.0
1.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
1.0
1.0
0.0
1.0
0.0
0.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
0.0
0.0
1.0
0.0
1.0
0.0
0.0
1.0
1.0
0.0
1.0
0.0
1.0
0.0
1.0


In [21]:
omc

array([ 0.057,  0.114,  0.951, ..., -0.7  , -0.43 , -0.32 ])

In [22]:
omc = abs(omc)

In [23]:
prcnt_bdy = omc/hml
prcnt_bdy *= 100

In [24]:
prcnt_bdy

array([ 7.27969349,  8.96226415, 70.81161579, ..., 76.08695652,
       25.90361446, 43.24324324])

In [25]:
topwick = np.zeros(len(high))
for i in range(len(high)):
    topwick[i] = (high[i] - max(opn[i],cls[i]))

topwick = topwick/hml
topwick *= 100
topwick

array([ 3.57598978, 20.91194969,  2.08488459, ...,  3.26086957,
        4.81927711, 16.21621622])

In [26]:
bottomwick = np.zeros(len(high))
for i in range(len(high)):
    bottomwick[i] = min(opn[i],cls[i]) - low[i]
bottomwick = bottomwick/hml
bottomwick = bottomwick*100
bottomwick

array([89.14431673, 70.12578616, 27.10349963, ..., 20.65217391,
       69.27710843, 40.54054054])

In [27]:
sum = prcnt_bdy + topwick + bottomwick
sum

array([100., 100., 100., ..., 100., 100., 100.])

In [28]:
volume = data.loc[:,"Volume"].to_numpy()
volume

array([11700414, 21670048, 19553768, ..., 17326500, 40554952, 20138114],
      dtype=int64)

In [29]:
n = len(high)

In [30]:
three_day_window = 3
three_day_prev_avg = np.zeros(n-3)
three_day_avg = np.zeros(n-3)
for i in range(three_day_window,n):
    three_day_prev_avg[i-3] = (np.mean(volume[i-3:i]))
#print(prev_avg)
for i in range(0,n-3):
    three_day_avg[i] = (volume[i+3] - three_day_prev_avg[i])
#avg

In [31]:
np.array(three_day_avg)

array([-3396062.        , -7518655.33333333, -6055552.        , ...,
       -8063690.66666667, 18122344.33333333, -6250859.66666667])

In [32]:
np.array(three_day_prev_avg)

array([17641410.        , 18489721.33333333, 14923394.        , ...,
       25390190.66666667, 22432607.66666667, 26388973.66666667])

In [33]:
two_day_window = 2
two_day_prev_avg = np.zeros(n-2)
two_day_avg = np.zeros(n-2)
for i in range(two_day_window,n):
    two_day_prev_avg[i-2] = (np.mean(volume[i-2:i]))
#print(prev_avg)
for i in range(0,n-2):
      two_day_avg[i] = (volume[i+2] - two_day_prev_avg[i])
#avg

In [34]:
np.array(two_day_avg)


array([ 2868537. , -6366560. , -5928492. , ..., -7659161.5, 21248967.5,
       -8802612. ])

In [35]:
np.array(two_day_prev_avg)

array([16685231. , 20611908. , 16899558. , ..., 24985661.5, 19305984.5,
       28940726. ])

In [36]:
four_day_window = 4
four_day_prev_avg = np.zeros(n-4)
four_day_avg = np.zeros(n-4)
for i in range(four_day_window,n):
    four_day_prev_avg[i-4] = (np.mean(volume[i-4:i]))
#print(prev_avg)
for i in range(0,n-4):
    four_day_avg[i] = (volume[i+3] - four_day_prev_avg[i])
#avg

In [37]:
np.array(four_day_avg)

array([-2547046.5 , -5638991.5 , -4541664.  , ..., -5511530.5 ,
       -6047768.  , 13591758.25])

In [38]:
np.array(four_day_prev_avg)

array([16792394.5 , 16610057.5 , 13409506.  , ..., 26796999.5 ,
       23374268.  , 26963193.75])

In [39]:
five_day_window = 5
five_day_prev_avg = np.zeros(n-5)
five_day_avg = np.zeros(n-5)
for i in range(five_day_window,n):
    five_day_prev_avg[i-5] = (np.mean(volume[i-5:i]))
#print(prev_avg)
for i in range(0,n-5):
    five_day_avg[i] = (volume[i+5] - five_day_prev_avg[i])
#avg

In [40]:
np.array(five_day_prev_avg)

array([15628128.8, 15061614.4, 12896288. , ..., 27333913.4, 24902899.6,
       26810404.8])

In [41]:
np.array(five_day_avg)

array([ -6760286.8,  -4218198.4,   3117265. , ..., -10007413.4,
        15652052.4,  -6672290.8])

In [42]:
len(three_day_avg)

4698

In [43]:
len(three_day_prev_avg)

4698

In [44]:
three_day_avg

array([-3396062.        , -7518655.33333333, -6055552.        , ...,
       -8063690.66666667, 18122344.33333333, -6250859.66666667])

In [45]:
three_day_prev_avg

array([17641410.        , 18489721.33333333, 14923394.        , ...,
       25390190.66666667, 22432607.66666667, 26388973.66666667])

In [46]:
type(three_day_avg)

numpy.ndarray

In [47]:
per_three_day = three_day_avg / three_day_prev_avg

In [48]:
per_three_day = per_three_day * 100

In [49]:
per_three_day

array([-19.25051342, -40.66397323, -40.57757907, ..., -31.75907882,
        80.78572319, -23.68739211])

In [50]:
type(two_day_avg)

numpy.ndarray

In [51]:
type(four_day_avg)

numpy.ndarray

In [52]:
type(five_day_avg)

numpy.ndarray

In [53]:
per_two_day = two_day_avg / two_day_prev_avg

In [54]:
per_two_day = per_two_day * 100

In [55]:
per_two_day

array([ 17.19207244, -30.88777613, -35.08075182, ..., -30.65422743,
       110.06414876, -30.41600269])

In [56]:
per_four_day = four_day_avg / four_day_prev_avg

In [57]:
per_four_day = per_four_day * 100

In [58]:
per_four_day

array([-15.16785769, -33.94925936, -33.86898816, ..., -20.56771505,
       -25.87361452,  50.40856204])

In [59]:
per_five_day = five_day_avg / five_day_prev_avg

In [60]:
per_five_day = per_five_day * 100

In [61]:
per_five_day

array([-43.25717357, -28.00628331,  24.17180044, ..., -36.61171108,
        62.85232905, -24.88694538])

In [62]:
type(topwick)

numpy.ndarray

In [63]:
type(bottomwick)

numpy.ndarray

In [64]:
wick = topwick + bottomwick
wick


array([92.72030651, 91.03773585, 29.18838421, ..., 23.91304348,
       74.09638554, 56.75675676])

In [65]:
len(wick)

4701

In [66]:
len(omc)

4701

In [67]:
for i in range(4701):
    if(omc[i] == 0):
        omc[i] = 1e9

In [68]:
prcnt_wick_by_body = wick / omc

In [69]:
for i in range(4701):
    if(omc[i] == 0):
        print(i)

In [70]:
type(bnry_omc)

numpy.ndarray

In [71]:
for i in range(4701):
    if(omc[i] > 0):
        print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975


In [72]:
three_day_bnry_window = 3
bnry_sum_three_day = np.zeros(4701)

for i in range(3,4701):
    bnry_sum_three_day[i-3] = (np.sum(bnry_omc[i-3:i]))


In [73]:
print(bnry_sum_three_day)

[0. 1. 2. ... 0. 0. 0.]


In [74]:
two_day_bnry_window = 2
bnry_sum_two_day = np.zeros(4701)

for i in range(2,4701):
    bnry_sum_two_day[i-2] = (np.sum(bnry_omc[i-2:i]))

In [75]:
print(bnry_sum_two_day)

[0. 0. 1. ... 2. 0. 0.]


In [76]:
four_day_bnry_window = 4
bnry_sum_four_day = np.zeros(4701)

for i in range(4,4701):
    bnry_sum_four_day[i-4] = (np.sum(bnry_omc[i-4:i]))

In [77]:
five_day_bnry_window = 5
bnry_sum_five_day = np.zeros(4701)

for i in range(5,4701):
    bnry_sum_five_day[i-5] = (np.sum(bnry_omc[i-5:i]))

In [78]:
print(bnry_sum_four_day)
print(bnry_sum_five_day)

[1. 2. 2. ... 0. 0. 0.]
[2. 2. 3. ... 0. 0. 0.]


In [79]:
for i in range(4701):
    print(bnry_sum_four_day[i])

1.0
2.0
2.0
3.0
2.0
1.0
1.0
1.0
2.0
2.0
3.0
2.0
1.0
1.0
1.0
2.0
2.0
3.0
3.0
3.0
3.0
2.0
2.0
1.0
1.0
2.0
2.0
3.0
4.0
4.0
3.0
2.0
1.0
0.0
0.0
0.0
1.0
1.0
2.0
3.0
3.0
4.0
3.0
3.0
3.0
2.0
3.0
2.0
1.0
1.0
0.0
1.0
2.0
3.0
3.0
3.0
2.0
2.0
3.0
2.0
3.0
2.0
1.0
1.0
1.0
2.0
3.0
4.0
4.0
3.0
3.0
2.0
1.0
2.0
2.0
3.0
4.0
4.0
3.0
3.0
3.0
3.0
3.0
2.0
2.0
2.0
3.0
3.0
2.0
2.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
2.0
3.0
2.0
2.0
1.0
1.0
2.0
3.0
4.0
3.0
2.0
1.0
1.0
2.0
3.0
4.0
3.0
2.0
2.0
1.0
1.0
2.0
1.0
1.0
2.0
1.0
1.0
2.0
1.0
2.0
2.0
2.0
2.0
2.0
3.0
3.0
4.0
4.0
3.0
3.0
3.0
2.0
2.0
2.0
1.0
1.0
1.0
1.0
2.0
2.0
3.0
2.0
2.0
3.0
3.0
3.0
2.0
2.0
1.0
1.0
2.0
1.0
2.0
3.0
3.0
3.0
2.0
2.0
2.0
2.0
2.0
2.0
1.0
1.0
1.0
1.0
2.0
2.0
3.0
2.0
1.0
1.0
0.0
1.0
1.0
2.0
3.0
2.0
3.0
3.0
2.0
3.0
2.0
1.0
2.0
1.0
1.0
1.0
0.0
0.0
0.0
1.0
2.0
2.0
2.0
2.0
2.0
3.0
4.0
3.0
2.0
1.0
1.0
1.0
1.0
1.0
1.0
2.0
3.0
4.0
4.0
4.0
4.0
3.0
3.0
2.0
1.0
2.0
2.0
3.0
3.0
2.0
2.0
2.0
2.0
3.0
3.0
3.0
3.0
3.0
3.0
2.0
3.0
3.0


1.0
1.0
1.0
1.0
1.0
2.0
3.0
3.0
3.0
3.0
2.0
2.0
3.0
3.0
4.0
4.0
4.0
4.0
3.0
3.0
2.0
1.0
2.0
2.0
3.0
4.0
4.0
3.0
3.0
3.0
2.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
4.0
4.0
4.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
2.0
2.0
2.0
1.0
2.0
2.0
1.0
2.0
2.0
2.0
3.0
2.0
2.0
2.0
2.0
3.0
2.0
2.0
1.0
0.0
0.0
1.0
1.0
2.0
2.0
2.0
3.0
3.0
3.0
3.0
3.0
3.0
4.0
4.0
3.0
2.0
1.0
0.0
0.0
0.0
0.0
1.0
2.0
3.0
4.0
3.0
3.0
3.0
3.0
3.0
3.0
2.0
1.0
2.0
2.0
2.0
2.0
1.0
0.0
1.0
1.0
2.0
2.0
1.0
1.0
1.0
2.0
2.0
2.0
2.0
2.0
2.0
3.0
2.0
2.0
2.0
1.0
1.0
1.0
2.0
2.0
2.0
1.0
0.0
0.0
1.0
2.0
3.0
4.0
4.0
3.0
3.0
3.0
2.0
2.0
2.0
2.0
3.0
3.0
3.0
3.0
3.0
4.0
3.0
2.0
2.0
1.0
2.0
2.0
1.0
2.0
1.0
1.0
2.0
1.0
1.0
2.0
2.0
3.0
4.0
4.0
4.0
3.0
2.0
1.0
1.0
2.0
2.0
3.0
3.0
3.0
3.0
2.0
2.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
2.0
2.0
2.0
3.0
3.0
4.0
3.0
2.0
2.0
1.0
1.0
1.0
1.0
2.0
2.0
3.0
2.0
2.0
3.0
3.0
3.0
3.0
3.0
2.0
2.0
1.0
1.0
1.0
2.0
3.0
2.0
3.0
3.0
3.0
4.0
4.0
4.0
3.0
3.0
3.0
3.0
3.0
3.0
2.0
2.0
2.0
1.0
2.0
1.0
2.0
3.0
3.0
3.0
2.0
2.0
1.0
2.0
2.0
1.0


In [84]:
    #count holidays
    import os
    import pandas as pd
    import numpy as np
    from datetime import date
    df = pd.read_csv('qqq.us.txt')
    arr = df.to_numpy()
    #print(arr)
    ans = []
    holidays = []
    for i in arr:
        t = []
        for j in i:
            t.append(j)
        ans.append(t)
    #print(ans)
    holidays.append(0)
    for i in range(1, len(ans)):
        str1 = ans[i-1][0]
        str2 = ans[i][0]
        date1 = []
        date2 = []
        s = ""
        for c in str1:
            if(c == '-'):
                date1.append(int(s))
                s = ""
            else:
                s = s + str(c)
        date1.append(int(s))
        s = ""
        for c in str2:
            if(c == '-'):
                date2.append(int(s))
                s = ""
            else:
                s = s + str(c)
        date2.append(int(s))
        d1 = date(date1[0], date1[1], date1[2])
        d2 = date(date2[0], date2[1], date2[2])
        holidays.append((d2 - d1).days - 1)
    print(len(holidays))
    print(len(ans))


4701
4701


In [88]:
for i in range(len(ans)):
    ans[i].append(hml[i])
    ans[i].append(prcnt_bdy[i])
    ans[i].append(topwick[i])
    ans[i].append(bottomwick[i])
    ans[i].append(bnry_omc[i])
    ans[i].append(prcnt_wick_by_body[i])
    ans[i].append(bnry_sum_two_day[i])
    ans[i].append(bnry_sum_three_day[i])
    ans[i].append(bnry_sum_four_day[i])
    ans[i].append(bnry_sum_five_day[i])
    ans[i].append(holidays[i])

print(ans)

    

[['1999-03-10', 45.722, 45.75, 44.967, 45.665, 11700414, 0, 0.7830000000000013, 7.279693486590302, 3.5759897828861615, 89.14431673052353, 0.0, 1626.6720440948452, 0.0, 0.0, 1.0, 2.0, 0.7830000000000013, 7.279693486590302, 3.5759897828861615, 89.14431673052353, 0.0, 1626.6720440948452, 0.0, 0.0, 1.0, 2.0, 0, 0.7830000000000013, 7.279693486590302, 3.5759897828861615, 89.14431673052353, 0.0, 1626.6720440948452, 0.0, 0.0, 1.0, 2.0, 0, 0.7830000000000013, 7.279693486590302, 3.5759897828861615, 89.14431673052353, 0.0, 1626.6720440948452, 0.0, 0.0, 1.0, 2.0, 0], ['1999-03-11', 45.994, 46.26, 44.988, 45.88, 21670048, 0, 1.2719999999999985, 8.962264150943188, 20.911949685534477, 70.12578616352233, 0.0, 798.5766302549039, 0.0, 1.0, 2.0, 2.0, 1.2719999999999985, 8.962264150943188, 20.911949685534477, 70.12578616352233, 0.0, 798.5766302549039, 0.0, 1.0, 2.0, 2.0, 0, 1.2719999999999985, 8.962264150943188, 20.911949685534477, 70.12578616352233, 0.0, 798.5766302549039, 0.0, 1.0, 2.0, 2.0, 0, 1.271999